js4
js-tasks-ru/jsbasic-20230428_nariman-gasanzade pull request #6
Opened 2023-05-26 12:59 UTC by Jokerlop

2023-05-26 13:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-26 13:10 UTC, SinimaWath requested changes

2023-05-26 13:10 UTC, SinimaWath commented on 5-module/2-task/index.js
> +    }
можно упростить до: `text.hidden = !text.hidden`

2023-05-26 13:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-30 13:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-05-30 16:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-06-01 13:12 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-06-01 18:56 UTC, SinimaWath approved these changes

2023-06-01 18:56 UTC, merged